In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
import matplotlib as plt
import re as ree
import requests
import csv
import datetime
import time
import random

In [2]:
def vv4(row):
    row = str(row)
    X = [1,1,1]
    X[0] = row[0:4]
    X[1] = row[4:6]
    X[2] = row[6:8]
    return X[0]+'-'+X[1]+'-'+X[2]

def vv(row):
    X = row.split('-')
    return X[0]+X[1]+X[2]

def DriveYearMonthDay(d):
    d['jalaliDate'] = d['jalaliDate'].astype(str)
    d['Year'] = d['jalaliDate'].str[0:4]
    d['Month'] = d['jalaliDate'].str[4:6]
    d['Day'] = d['jalaliDate'].str[6:8]
    d['jalaliDate'] = d['jalaliDate'].astype(int)
    return d

def convert_ar_characters(input_str):

    mapping = {
        'ك': 'ک',
        'گ':'گ',
        'دِ': 'د',
        'بِ': 'ب',
        'زِ': 'ز',
        'ذِ': 'ذ',
        'شِ': 'ش',
        'سِ': 'س',
        'ى': 'ی',
        'ي': 'ی'
    }
    return _multiple_replace(mapping, input_str)


def _multiple_replace(mapping, text):
    pattern = "|".join(map(ree.escape, mapping.keys()))
    return ree.sub(pattern, lambda m: mapping[m.group()], str(text))
def vv2(row):
    X = row.split('/')
    return X[0]+X[1]+X[2]
def vv3(row):
    X = row.split('/')
    if len(X[0])<4:
        X[0] = '13' + X[0]
    if len(X[1])<2:
        X[1] = '0'+X[1]
    if len(X[2])<2:
        X[2] = '0'+X[2]
    return X[0]+X[1]+X[2]
def vv5(row):
    X = row.split('/')
    return X[0]

In [3]:
path = r"C:\Users\RA\Desktop\RA_Aghajanzadeh\Data\\"
# path = r"H:\Economics\Finance(Prof.Heidari-Aghajanzadeh)\Data\\"

In [6]:


n = path + 'Cleaned_Stocks_Holders_1399-09-12_From94.csv'
df = pd.read_csv(n)

df = df.drop(df.loc[df['Holder']=='شخص حقیقی'].index)
df = df.drop(df[(df['Trade']=='No')&((df['close_price']==10)|(df['close_price']==1000)|(df['close_price']==10000)|(df['close_price']==100000))].index)
df = df.drop(df[(df['symbol'] == 'وقوام')&(df['close_price'] == 1000)].index)
symbols = [ 'سپرده','هما','وهنر-پذیره','نکالا','تکالا','اکالا','توسعه گردشگری ','وآفر','ودانا','نشار','نبورس','چبسپا','بدکو','چکارم','تراک','کباده','فبستم','تولیددارو','قیستو','خلیبل','پشاهن','قاروم','هوایی سامان','کورز','شلیا','دتهران','نگین','کایتا','غیوان','تفیرو','سپرمی','بتک']
df = df.drop(df[df['symbol'].isin(symbols)].index)
df = df.drop(df[df.group_name== 'صندوق سرمایه گذاری قابل معامله'].index)
df = df.drop(df[(df.symbol == 'اتکای')&(df.close_price == 1000)].index)

In [7]:
HolderData = df

In [8]:
# path = r"H:\Economics\Finance(Prof.Heidari-Aghajanzadeh)\Data"

n1 = path + 'Stocks_Prices_1399-09-12' + '.csv'
df1 = pd.read_csv(n1)

df1['jalaliDate'] = df1['jalaliDate'].apply(vv)
df = df1
symbols = [ 'سپرده','هما','وهنر-پذيره','نکالا','تکالا','اکالا','توسعه گردشگری ','وآفر','ودانا','نشار','نبورس','چبسپا','بدکو','چکارم','تراک','کباده','فبستم','تولیددارو','قیستو','خلیبل','پشاهن','قاروم','هوایی سامان','کورز','شلیا','دتهران','نگین','کایتا','غیوان','تفیرو','سپرمی','بتک']
df = df.drop(df[df['name'].isin(symbols)].index)
df = df.drop(df[df.group_name== 'صندوق سرمایه گذاری قابل معامله'].index)


df = df.drop(df[(df.name == 'اتکای')&(df.close_price == 1000)].index)
df = df.drop_duplicates()
df = df.drop(df.loc[(df['volume'] == 0)].index).sort_values(by =['name','jalaliDate']).drop(columns = ['volume','quantity']).rename(columns = {'name':'symbol'})
df = DriveYearMonthDay(df)

In [9]:
PriceData = pd.DataFrame()
PriceData = PriceData.append(df[['jalaliDate', 'date', 'symbol','close_price','group_id']])
PriceData['date1'] = PriceData['date'].apply(vv4)
PriceData['date1'] = pd.to_datetime(PriceData['date1']) 
PriceData['week_of_year'] = PriceData['date1'].dt.week 
PriceData['year_of_year'] = PriceData['date1'].dt.year
gg =PriceData.groupby('symbol')
PriceData['Ret'] = gg['close_price'].pct_change(periods = 1)*100
PriceData.head()

,jalaliDate,date,symbol,close_price,group_id,date1,week_of_year,year_of_year,Ret
1727814,13900422,20110713,آ س پ,3100.0,70,2011-07-13,28,2011,NaN
1727813,13900425,20110716,آ س پ,3252.0,70,2011-07-16,28,2011,4.903226
1727812,13900427,20110718,آ س پ,3264.0,70,2011-07-18,29,2011,0.369004
1727811,13900428,20110719,آ س پ,3203.0,70,2011-07-19,29,2011,-1.868873
1727810,13900429,20110720,آ س پ,3147.0,70,2011-07-20,29,2011,-1.748361

In [10]:
n = path + 'Factors-Daily.xlsx'
Factors = pd.read_excel(n)

In [11]:
Factors.tail()

      jalaliDate      date       SMB       HML  Winner_Loser  Market_return
2882    13990908  20201128 -0.680105 -1.598209      1.435511       1.728555
2883    13990909  20201129 -1.619483 -0.646124     -0.366239       2.616847
2884    13990910  20201130 -1.062186  1.714601     -0.160517       2.714100
2885    13990911  20201201 -0.595752  0.555956     -0.071474       0.529881
2886    13990912  20201202  0.351218 -0.764257      0.124712      -0.185540

In [12]:
PriceData = PriceData.merge(Factors,on = ['jalaliDate','date']).sort_values(by =['symbol','date']).reset_index(drop=True).dropna()

In [13]:
PriceData.head()

,jalaliDate,date,symbol,close_price,group_id,date1,week_of_year,year_of_year,Ret,SMB,HML,Winner_Loser,Market_return
1,13900425,20110716,آ س پ,3252.0,70,2011-07-16,28,2011,4.903226,0.329833,0.112264,1.671435,0.256107
2,13900427,20110718,آ س پ,3264.0,70,2011-07-18,29,2011,0.369004,-0.431230,-1.048659,4.257639,0.459158
3,13900428,20110719,آ س پ,3203.0,70,2011-07-19,29,2011,-1.868873,-1.239107,-1.245822,-1.200158,0.138590
4,13900429,20110720,آ س پ,3147.0,70,2011-07-20,29,2011,-1.748361,-3.056799,-1.671610,0.581469,0.438464
5,13900501,20110723,آ س پ,3163.0,70,2011-07-23,29,2011,0.508421,-0.453838,-0.725122,-0.621002,0.843834

In [14]:
n = path + 'RiskFree.xlsx'
df3 = pd.read_excel(n)
df3 = df3.rename(columns = {'Unnamed: 2' : 'Year'})
df3['YM'] = df3['YM'].astype(str)
df3['YM'] = df3['YM'] + '00'
df3['YM'] = df3['YM'].astype(int)
df4 = PriceData
df4['RiskFree'] = np.nan
df4['jalaliDate'] = df4['jalaliDate'].astype(int)
for i in df3.YM:
    df4.loc[df4.jalaliDate>= i,'RiskFree'] = df3.loc[df3['YM'] == i ].iloc[0,1]/12/52/7

In [15]:
PriceData = df4
PriceData['EMarketRet'] = PriceData['Market_return'] - PriceData['RiskFree']
PriceData['ERet'] = PriceData['Ret'] - PriceData['RiskFree']

In [16]:
PriceData.head()

,jalaliDate,date,symbol,close_price,group_id,date1,week_of_year,year_of_year,Ret,SMB,HML,Winner_Loser,Market_return,RiskFree,EMarketRet,ERet
1,13900425,20110716,آ س پ,3252.0,70,2011-07-16,28,2011,4.903226,0.329833,0.112264,1.671435,0.256107,0.003892,0.252215,4.899334
2,13900427,20110718,آ س پ,3264.0,70,2011-07-18,29,2011,0.369004,-0.431230,-1.048659,4.257639,0.459158,0.003892,0.455266,0.365112
3,13900428,20110719,آ س پ,3203.0,70,2011-07-19,29,2011,-1.868873,-1.239107,-1.245822,-1.200158,0.138590,0.003892,0.134698,-1.872764
4,13900429,20110720,آ س پ,3147.0,70,2011-07-20,29,2011,-1.748361,-3.056799,-1.671610,0.581469,0.438464,0.003892,0.434572,-1.752253
5,13900501,20110723,آ س پ,3163.0,70,2011-07-23,29,2011,0.508421,-0.453838,-0.725122,-0.621002,0.843834,0.003892,0.839942,0.504529

In [17]:
n1 = path + "Industry indexes 1399-09-28.csv"
df1 = pd.read_csv(n1)
df1.date = df1.date.apply(vv3)
df1 = df1.drop(columns = ['Unnamed: 0'])
df1 = df1.drop(df1[(df1.index_id == 'EWI')|(df1.index_id == 'overall_index')].index)
df1.index_id = df1.index_id.astype(int)
df1.date = df1.date.astype(int)
gg = df1.groupby('index_id')
df1['gReturn'] = gg['index'].pct_change(periods = 1)*100
fkey = zip(list(df1.index_id),list(df1.date))
mapingdict = dict(zip(fkey,df1['gReturn']))
PriceData['gReturn'] = PriceData.set_index(['group_id','jalaliDate']).index.map(mapingdict)
PriceData['EgReturn'] = PriceData['gReturn'] - PriceData['RiskFree']

In [18]:
wg = PriceData.groupby(['symbol'])
def FourFactor(g):
    try:
        y = 'ERet'
        x = ['EMarketRet','HML','SMB','Winner_Loser']
        model = sm.OLS(g[y], sm.add_constant(g[x])).fit()
        g['4-Residual'] = g ['ERet'] - (model.params[0] + model.params[1]*g['EMarketRet'] + model.params[2]*g['HML']  + model.params[3]*g['SMB']  + model.params[4]*g['Winner_Loser']) 
    except:
        print(g.symbol.iloc[0])
        g = pd.DataFrame()
    return g

def FiveFactor(g):
    try:
        y = 'ERet'
        x = ['EMarketRet','HML','SMB','Winner_Loser','EgReturn']
        model = sm.OLS(g[y], sm.add_constant(g[x])).fit()
        g['5-Residual'] = g ['ERet'] - (model.params[0] + model.params[1]*g['EMarketRet'] + model.params[2]*g['HML']  + model.params[3]*g['SMB']  + model.params[4]*g['Winner_Loser'] + model.params[5]*g['EgReturn']) 
    except:
        print(g.symbol.iloc[0])
        g = pd.DataFrame()
    return g

def TwoFactor(g):
    try:
        y = 'ERet'
        x = ['EMarketRet','EgReturn']
        model = sm.OLS(g[y], sm.add_constant(g[x])).fit()
        g['2-Residual'] = g ['ERet'] - (model.params[0] + model.params[1]*g['EMarketRet'] + model.params[2]*g['EgReturn']) 
    except:
        print(g.symbol.iloc[0])
        g = pd.DataFrame()
    return g

re = wg.apply(FourFactor)
print('Fourfactor done')
re2 = wg.apply(FiveFactor)
re['5-Residual'] = re2['5-Residual']
print('Fivefactor done')

re2 = wg.apply(TwoFactor)
re['2-Residual'] = re2['2-Residual']
print('Twofactor done')

re = re.reset_index(drop=True)
col = 'symbol'
re[col] = re[col].apply(lambda x: convert_ar_characters(x))

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2389: FutureWarning: Method .ptp is deprecated and will be removed in a future version. Use numpy.ptp instead.
  return ptp(axis=axis, out=out, **kwargs)

پالايش
Fourfactor done
آتيمس
آساس
آسام
آساميد
آكورد
آوا
آگاس
ارزش
ارمغان
اطلس
اعتماد
افران
افق ملت
البرز
الماس
امين يكم
اوان
اوصتا
اپرداز
بالاس
بدكو
بذر
بميلا
بمپنا
بورس
تصميم
توسعه گردشگري
ثروتم
حاريا
حخزر
حفاري
خاتم
خبازرس
خصدرا
دارا
دارا يكم
داريك
دمعيار
رفاه
سخند
سرو
سمگا
سپر
صايند
صنوين
فيروزا
قاسم
كاردان
كاريس
كمند
كيان
ماديرا
مبين
مدير
نگين
هاي وب
ونيرو
وهنر
ياقوت
پارند
پالايش
گدنا
گشان
گكوثر
گكيش
گنجين
گپارس
Fivefactor done
آتيمس
آساس
آسام
آساميد
آكورد
آوا
آگاس
ارزش
ارمغان
اطلس
اعتماد
افران
افق ملت
البرز
الماس
امين يكم
اوان
اوصتا
اپرداز
بالاس
بدكو
بذر
بميلا
بمپنا
بورس
تصميم
توسعه گردشگري
ثروتم
حاريا
حخزر
حفاري
خاتم
خبازرس
خصدرا
دارا
دارا يكم
داريك
دمعيار
رفاه
سخند
سرو
سمگا
سپر
صايند
صنوين
فيروزا
قاسم
كاردان
كاريس
كمند
كيان
ماديرا
مبين
مدير
نگين
هاي وب
ونيرو
وهنر
ياقوت
پارند
پالايش
گدنا
گشان
گكوثر
گكيش
گنجين
گپارس
Twofactor done

In [19]:
residuals = re[re.jalaliDate>13940000]

In [20]:
A = set(residuals.symbol)
len(set(residuals.symbol))

699

In [21]:
C = set(HolderData.symbol)
len(set(HolderData.symbol))

612

In [22]:
# HolderData = df

In [23]:
fkey = zip(list(residuals.symbol),list(residuals.date))
mapingdict = dict(zip(fkey,residuals['4-Residual']))
HolderData['4-Residual'] = HolderData.set_index(['symbol','date']).index.map(mapingdict)
print('4-Residual done')
fkey = zip(list(residuals.symbol),list(residuals.date))
mapingdict = dict(zip(fkey,residuals['5-Residual']))
HolderData['5-Residual'] = HolderData.set_index(['symbol','date']).index.map(mapingdict)
print('5-Residual done')
fkey = zip(list(residuals.symbol),list(residuals.date))
mapingdict = dict(zip(fkey,residuals['2-Residual']))
HolderData['2-Residual'] = HolderData.set_index(['symbol','date']).index.map(mapingdict)
print('2-Residual done')
fkey = zip(list(residuals.symbol),list(residuals.date))
mapingdict = dict(zip(fkey,residuals['Ret']))
HolderData['Ret'] = HolderData.set_index(['symbol','date']).index.map(mapingdict)
print('Ret done')

4-Residual done
5-Residual done
2-Residual done
Ret done

In [24]:
HolderData = HolderData.drop(HolderData[HolderData['4-Residual'].isnull()].index)

In [25]:
len(HolderData)
# [HolderData['4-Residual'].isnull()]

2627705

In [26]:

B = set(HolderData.symbol)
len(set(HolderData.symbol))

609

In [27]:
HolderData.jalaliDate.iloc[0]

13940105

In [28]:
df = HolderData

In [29]:
Holders = list(set(df.Holder))
Holders.sort()
ids = list(range(len(Holders)))
mapingdict = dict(zip(Holders, ids))
df['Holder_id'] = df['Holder'].map(mapingdict)

symbols = list(set(df.symbol))
symbols.sort()
ids = list(range(len(symbols)))
mapingdict = dict(zip(symbols, ids))
df['id'] = df['symbol'].map(mapingdict)

In [30]:
df['date1'] = df['date'].apply(vv4)
df['date1'] = pd.to_datetime(df['date1']) 
df['week_of_year'] = df['date1'].dt.week 
df['month_of_year'] = df['date1'].dt.month 
df['year_of_year'] = df['date1'].dt.year

In [31]:
df['MarketCap'] = df['close_price'] * df['shrout']

In [32]:
market = df.groupby(['date','symbol']).first().reset_index()[['jalaliDate','date','symbol','MarketCap']]
gm = market.groupby(['date'])

market['Percentile_Rank'] = gm.MarketCap.rank(pct = True) 
fkey = zip(list(market.symbol),list(market.date))
mapingdict = dict(zip(fkey,market['Percentile_Rank']))
df['Percentile_Rank'] = df.set_index(['symbol','date']).index.map(mapingdict)

In [33]:
df.head()

,date,jalaliDate,symbol,stock_id,group_name,group_id,Holder,nshares,type,Percent,...,2-Residual,Ret,Holder_id,id,date1,week_of_year,month_of_year,year_of_year,MarketCap,Percentile_Rank
2420,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,38798288.0,insurance,4.84,...,1.106068,0.88,1147,0,2015-03-25,13,3,2015,1.008800e+12,0.371542
2421,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,وغدیر,67896459.0,investment,8.48,...,1.106068,0.88,1652,0,2015-03-25,13,3,2015,1.008800e+12,0.371542
2422,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ایرانیان اطلس,121316125.0,private,15.16,...,1.106068,0.88,204,0,2015-03-25,13,3,2015,1.008800e+12,0.371542
2423,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صنعتی و بازرگانی غدیر,164077508.0,private,20.50,...,1.106068,0.88,1264,0,2015-03-25,13,3,2015,1.008800e+12,0.371542
2424,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,321682470.0,private,40.21,...,1.106068,0.88,540,0,2015-03-25,13,3,2015,1.008800e+12,0.371542

In [34]:
n2 = path + '\\balance sheet - 9811' + '.xlsx'
df2 = pd.read_excel(n2)
df2 = df2.iloc[:,[0,4,13,-7]]
df2.rename(columns={ df2.columns[0]: "symbol" ,df2.columns[1]: "date" ,df2.columns[2]: "BookValue" ,df2.columns[3] : "Capital"}, inplace = True)
# df2['shrout'] = df2['Capital'] * 100
df2['Year'] = df2['date'].apply(vv5)
df2['Year'] = df2['Year'].astype(str)
df2 = df2.drop(columns = ['date','Capital'])
col = 'symbol'
df2[col] = df2[col].apply(lambda x: convert_ar_characters(x))

In [35]:
df = DriveYearMonthDay(df)
df = df.merge(df2,on=['symbol','Year'],how = 'left')
df['BookValue'] = df['BookValue'].fillna(method='ffill')
df = df.drop(columns = ['Year', 'Month', 'Day'])
df['BookToMarket'] = df['MarketCap']/1e6/df['BookValue']

In [36]:
gg = df.groupby('date')
df['BookToMarket'] = gg.BookToMarket.rank(pct = True)

In [37]:
df.head()

,date,jalaliDate,symbol,stock_id,group_name,group_id,Holder,nshares,type,Percent,...,Holder_id,id,date1,week_of_year,month_of_year,year_of_year,MarketCap,Percentile_Rank,BookValue,BookToMarket
0,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,38798288.0,insurance,4.84,...,1147,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602
1,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,وغدیر,67896459.0,investment,8.48,...,1652,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602
2,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ایرانیان اطلس,121316125.0,private,15.16,...,204,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602
3,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صنعتی و بازرگانی غدیر,164077508.0,private,20.50,...,1264,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602
4,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,321682470.0,private,40.21,...,540,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602

In [38]:
df.columns

Index(['date', 'jalaliDate', 'symbol', 'stock_id', 'group_name', 'group_id',
       'Holder', 'nshares', 'type', 'Percent', 'shrout', 'close_price',
       'Number_Change', 'Percent_Change', 'Condition', 'Trade', '4-Residual',
       '5-Residual', '2-Residual', 'Ret', 'Holder_id', 'id', 'date1',
       'week_of_year', 'month_of_year', 'year_of_year', 'MarketCap',
       'Percentile_Rank', 'BookValue', 'BookToMarket'],
      dtype='object')

In [39]:
HolderData['Percent_Change'] = HolderData['Percent_Change'].replace('-',np.nan)
HolderData['Percent_Change'] = HolderData['Percent_Change'].astype(float)
aa = HolderData.groupby('Holder_id').Percent_Change.mean().to_frame().sort_values(by = ['Percent_Change']) 
aa = aa[~aa.Percent_Change.isnull()].reset_index()
aa["Holder_act"] = 0
aa.loc[aa.Percent_Change > aa.Percent_Change.median(),"Holder_act"] = 1
mapingdict = dict(zip(aa['Holder_id'],aa['Holder_act']))
df['Holder_act'] = df['Holder_id'].map(mapingdict)

In [41]:
df.head()

,date,jalaliDate,symbol,stock_id,group_name,group_id,Holder,nshares,type,Percent,...,id,date1,week_of_year,month_of_year,year_of_year,MarketCap,Percentile_Rank,BookValue,BookToMarket,Holder_act
0,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,38798288.0,insurance,4.84,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
1,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,وغدیر,67896459.0,investment,8.48,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
2,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ایرانیان اطلس,121316125.0,private,15.16,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
3,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صنعتی و بازرگانی غدیر,164077508.0,private,20.50,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
4,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,321682470.0,private,40.21,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0

In [4]:
df.to_csv(path  + 'Holder_Residual.csv',index = False)
# df = pd.read_csv(path + 'Holder_Residual.csv')

In [5]:
df.head()

,date,jalaliDate,symbol,stock_id,group_name,group_id,Holder,nshares,type,Percent,...,id,date1,week_of_year,month_of_year,year_of_year,MarketCap,Percentile_Rank,BookValue,BookToMarket,Holder_act
0,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,38798288.0,insurance,4.84,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
1,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,وغدیر,67896459.0,investment,8.48,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
2,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ایرانیان اطلس,121316125.0,private,15.16,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
3,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صنعتی و بازرگانی غدیر,164077508.0,private,20.50,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
4,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,321682470.0,private,40.21,...,0,2015-03-25,13,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0

In [83]:
df.head()
df.loc[df.week_of_year%2 == 1,'week_of_year'] = df.loc[df.week_of_year%2 == 1]['week_of_year']-1
df.head()

,date,jalaliDate,symbol,stock_id,group_name,group_id,Holder,nshares,type,Percent,...,id,date1,week_of_year,month_of_year,year_of_year,MarketCap,Percentile_Rank,BookValue,BookToMarket,Holder_act
0,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صندوق بیمه اجتماعی روستاییان و عشایر,38798288.0,insurance,4.84,...,0,2015-03-25,12,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
1,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,وغدیر,67896459.0,investment,8.48,...,0,2015-03-25,12,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
2,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ایرانیان اطلس,121316125.0,private,15.16,...,0,2015-03-25,12,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
3,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,صنعتی و بازرگانی غدیر,164077508.0,private,20.50,...,0,2015-03-25,12,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0
4,20150325,13940105,آ س پ,1.761747e+16,انبوه سازی، املاک و مستغلات,70.0,ثاخت,321682470.0,private,40.21,...,0,2015-03-25,12,3,2015,1.008800e+12,0.371542,1447582.0,0.44602,0.0

In [85]:
    def FCAPf(S_g,g):
        intersection = list(set.intersection(set(S_g.date), set(g.date)))
        if len(intersection) == 0 :
#             print('0')
            return
        f= Calculation(g,S_g)
        if len (f) == 0:
#             print("No")
            return
        f = MonthlyCalculation(f)        
        f = WeeklyCalculation(f)
        return f
    
    def Calculation(g,S_g):
        intersection = list(set.intersection(set(S_g.date), set(g.date)))
        g = g.loc[g.date.isin(intersection)]
        S_g = S_g.loc[S_g.date.isin(intersection)]
        a = g.merge(S_g , on = ['Holder_id','date','jalaliDate','week_of_year','month_of_year','year_of_year'])
        a = FCalculatio(a,g,S_g)
        if len(a) == 0:
            f = pd.DataFrame()
            return f
        a['SizeRatio'] = (a['MarketCap_x'])/(a['MarketCap_y'])
        f = a.groupby(['date','jalaliDate','id_x','id_y','week_of_year','month_of_year','year_of_year',
                           'group_name_x','group_name_y','Ret_x','Ret_y','SizeRatio','MarketCap_x',
                           'MarketCap_y','2-Residual_x','2-Residual_y','4-Residual_x','4-Residual_y',
                           '5-Residual_x','5-Residual_y','Percentile_Rank_x','Percentile_Rank_y',
                      'BookToMarket_x','BookToMarket_y'])['FCAPf','FCA',
                                                          'Holder_act_y','Holder_act_x'].sum().reset_index()
        a = a[['type_x','type_y']].drop_duplicates()
        a['Sametype'] = 0
        a.loc[a.type_x == a.type_y, 'Sametype'] = 1
        if a['Sametype'].sum() > 0 :
            f['Sametype'] = 1
        else:
            f['Sametype'] = 0
        
        
        
        f['Holder_act'] = 0
        f.loc[f['Holder_act_y']>0,'Holder_act'] = 1
        f.loc[f['Holder_act_x']>0,'Holder_act'] = 1
        f = f.drop(columns = ['Holder_act_y','Holder_act_x'])
        f['FCA'] = f['FCA']**2
        f['size1'] = 0
        f.loc[f.MarketCap_x>f.MarketCap_y,'size1'] = f[f.MarketCap_x>f.MarketCap_y]['Percentile_Rank_x']
        f.loc[f.MarketCap_x<f.MarketCap_y,'size1'] = f[f.MarketCap_x<f.MarketCap_y]['Percentile_Rank_y']
        f['size2'] = 0
        f.loc[f.MarketCap_x>f.MarketCap_y,'size2'] = f[f.MarketCap_x>f.MarketCap_y]['Percentile_Rank_y']
        f.loc[f.MarketCap_x<f.MarketCap_y,'size2'] = f[f.MarketCap_x<f.MarketCap_y]['Percentile_Rank_x']
        f['SameSize'] = -1 * abs(f['size2'] -f['size1'])
        f['sgroup'] = 0
        f.loc[f.group_name_x == f.group_name_y,'sgroup'] = 1
        f['B/M1'] = 0
        f.loc[f.MarketCap_x>f.MarketCap_y,'B/M1'] = f[f.MarketCap_x>f.MarketCap_y]['BookToMarket_x']
        f.loc[f.MarketCap_x<f.MarketCap_y,'B/M1'] = f[f.MarketCap_x<f.MarketCap_y]['BookToMarket_y']
        f['B/M2'] = 0
        f.loc[f.MarketCap_x>f.MarketCap_y,'B/M2'] = f[f.MarketCap_x>f.MarketCap_y]['BookToMarket_y']
        f.loc[f.MarketCap_x<f.MarketCap_y,'B/M2'] = f[f.MarketCap_x<f.MarketCap_y]['BookToMarket_x']
        f['SameB/M'] = -1 * abs(f['B/M2'] -f['B/M1'])
        
        return f
    
    def FCalculatio(a,g,S_g):
        if len(a) == 0:
            a = pd.DataFrame()
            return a
    #         a = g.merge(S_g , on = ['date','jalaliDate','week_of_year','month_of_year','year_of_year'])
    #         a['FCAPf'] = 0
    #         a['FCA'] = 0
        else: 
            a['FCAPf'] = (a['nshares_x']*a['close_price_x'] + a['nshares_y']*a['close_price_y'])/(a['shrout_x']*a['close_price_x'] + a['shrout_y']*a['close_price_y'])
            a['FCA'] = ((a['nshares_x']*a['close_price_x'])**0.5 + (a['nshares_y']*a['close_price_y'])**0.5)/((a['shrout_x']*a['close_price_x'])**0.5 + (a['shrout_y']*a['close_price_y'])**0.5)
        return a

In [86]:
    def MonthlyCalculation(f):
    
        f = MonthlyCorr(f)        
        
        ff = f.groupby(['year_of_year','month_of_year'])[['SizeRatio','MarketCap_x',
                                                          'MarketCap_y','Percentile_Rank_x',
                                                       'Percentile_Rank_y','size1','size2',
                                                          'SameSize','B/M1','B/M2','SameB/M']].mean().reset_index()
        
        vlist = ['SizeRatio', 'MarketCap_x','MarketCap_y', 'Percentile_Rank_x', 'Percentile_Rank_y', 'size1',
               'size2', 'SameSize','B/M1','B/M2','SameB/M']
        
        for i in vlist:
            TimeId = zip(list(ff.year_of_year),list(ff.month_of_year))
            mapingdict = dict(zip(TimeId,list(ff[i])))
            f['Monthly'+i] = f.set_index(['year_of_year','month_of_year']).index.map(mapingdict)
        
        mfcapf =  f.groupby(['year_of_year','month_of_year'])['FCAPf','FCA'].mean().reset_index()
        TimeId = zip(list(mfcapf.year_of_year),list(mfcapf.month_of_year))
        mapingdict = dict(zip(TimeId,list(mfcapf.FCAPf)))
        f['MonthlyFCAPf'] = f.set_index(['year_of_year','month_of_year']).index.map(mapingdict)
        TimeId = zip(list(mfcapf.year_of_year),list(mfcapf.month_of_year))
        mapingdict = dict(zip(TimeId,list(mfcapf.FCA)))
        f['MonthlyFCA'] = f.set_index(['year_of_year','month_of_year']).index.map(mapingdict)
                
        f['Monthlyρ_2_f'] = f['Monthlyρ_2'].shift(-1)
        f['Monthlyρ_4_f'] = f['Monthlyρ_4'].shift(-1)
        f['Monthlyρ_5_f'] = f['Monthlyρ_5'].shift(-1)
        return f
    def MonthlyCorr(f):
        
        fc = f.groupby(['year_of_year','month_of_year'])[['2-Residual_x','2-Residual_y',
                                                          '4-Residual_x','4-Residual_y',
                                                          '5-Residual_x','5-Residual_y']].corr().reset_index()
        
        TwoCor = fc.loc[fc.level_2 == '2-Residual_y'][['year_of_year','month_of_year',
                                                       '2-Residual_x']].rename(columns = {'2-Residual_x':'ρ_2'})
        FourCor = fc.loc[fc.level_2 == '4-Residual_y'][['year_of_year','month_of_year',
                                                        '4-Residual_x']].rename(columns = {'4-Residual_x':'ρ_4'})
        ThreeCor = fc.loc[fc.level_2 == '5-Residual_y'][['year_of_year','month_of_year',
                                                         '5-Residual_x']].rename(columns = {'5-Residual_x':'ρ_5'})
        
        TimeId = zip(list(TwoCor.year_of_year),list(TwoCor.month_of_year))
        mapingdict = dict(zip(TimeId,list(TwoCor.ρ_2)))
        f['Monthlyρ_2'] = f.set_index(['year_of_year','month_of_year']).index.map(mapingdict)
        
        TimeId = zip(list(FourCor.year_of_year),list(FourCor.month_of_year))
        mapingdict = dict(zip(TimeId,list(FourCor.ρ_4)))
        f['Monthlyρ_4'] = f.set_index(['year_of_year','month_of_year']).index.map(mapingdict)
        
        TimeId = zip(list(ThreeCor.year_of_year),list(ThreeCor.month_of_year))
        mapingdict = dict(zip(TimeId,list(ThreeCor.ρ_5)))
        f['Monthlyρ_5'] = f.set_index(['year_of_year','month_of_year']).index.map(mapingdict) 
        return f

In [87]:
    def WeeklyCalculation(f):
        
        f = WeeklyCorr(f)


        ff = f.groupby(['year_of_year','week_of_year'])[['SizeRatio','MarketCap_x','MarketCap_y','Percentile_Rank_x',
                                                       'Percentile_Rank_y','size1','size2','SameSize',
                                                         'B/M1','B/M2','SameB/M']].mean().reset_index()
        
        vlist = ['SizeRatio', 'MarketCap_x','MarketCap_y', 'Percentile_Rank_x', 'Percentile_Rank_y', 'size1',
               'size2', 'SameSize','B/M1','B/M2','SameB/M']
        
        for i in vlist:
            TimeId = zip(list(ff.year_of_year),list(ff.week_of_year))
            mapingdict = dict(zip(TimeId,list(ff[i])))
            f['Weekly'+i] = f.set_index(['year_of_year','week_of_year']).index.map(mapingdict) 



        wfcapf =  f.groupby(['year_of_year','week_of_year'])['FCAPf','FCA'].mean().reset_index()
        TimeId = zip(list(wfcapf.year_of_year),list(wfcapf.week_of_year))
        mapingdict = dict(zip(TimeId,list(wfcapf.FCAPf)))
        f['WeeklyFCAPf'] = f.set_index(['year_of_year','week_of_year']).index.map(mapingdict)  
        TimeId = zip(list(wfcapf.year_of_year),list(wfcapf.week_of_year))
        mapingdict = dict(zip(TimeId,list(wfcapf.FCA)))
        f['WeeklyFCA'] = f.set_index(['year_of_year','week_of_year']).index.map(mapingdict) 
        f['Weeklyρ_2_f'] = f['Weeklyρ_2'].shift(-1)
        f['Weeklyρ_4_f'] = f['Weeklyρ_4'].shift(-1)
        f['Weeklyρ_5_f'] = f['Weeklyρ_5'].shift(-1)
        return f
    
    def WeeklyCorr(f):
        fc = f.groupby(['year_of_year','week_of_year'])[['2-Residual_x','2-Residual_y',
                                                         '4-Residual_x','4-Residual_y',
                                                         '5-Residual_x','5-Residual_y']].corr().reset_index()
        
        TwoCor = fc.loc[fc.level_2 == '2-Residual_y'][['year_of_year','week_of_year',
                                                        '2-Residual_x']].rename(columns = {'2-Residual_x':'ρ_2'})
        FourCor = fc.loc[fc.level_2 == '4-Residual_y'][['year_of_year','week_of_year',
                                                        '4-Residual_x']].rename(columns = {'4-Residual_x':'ρ_4'})
        ThreeCor = fc.loc[fc.level_2 == '5-Residual_y'][['year_of_year','week_of_year',
                                                         '5-Residual_x']].rename(columns = {'5-Residual_x':'ρ_5'})
        
        TimeId = zip(list(TwoCor.year_of_year),list(TwoCor.week_of_year))
        mapingdict = dict(zip(TimeId,list(TwoCor.ρ_2)))
        f['Weeklyρ_2'] = f.set_index(['year_of_year','week_of_year']).index.map(mapingdict)
        
        TimeId = zip(list(FourCor.year_of_year),list(FourCor.week_of_year))
        mapingdict = dict(zip(TimeId,list(FourCor.ρ_4)))
        f['Weeklyρ_4'] = f.set_index(['year_of_year','week_of_year']).index.map(mapingdict)
        
        TimeId = zip(list(ThreeCor.year_of_year),list(ThreeCor.week_of_year))
        mapingdict = dict(zip(TimeId,list(ThreeCor.ρ_5)))
        f['Weeklyρ_5'] = f.set_index(['year_of_year','week_of_year']).index.map(mapingdict)
        
        return f

In [88]:
gdata = df.groupby(['id'])
g = gdata.get_group(0)
S_g = gdata.get_group(4)



FCAPf(S_g,g)

,date,jalaliDate,id_x,id_y,week_of_year,month_of_year,year_of_year,group_name_x,group_name_y,Ret_x,...,Weeklysize2,WeeklySameSize,WeeklyB/M1,WeeklyB/M2,WeeklySameB/M,WeeklyFCAPf,WeeklyFCA,Weeklyρ_2_f,Weeklyρ_4_f,Weeklyρ_5_f
0,20170329,13960109,0,4,13,3,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,3.703704,...,0.280928,-0.649485,0.857464,0.344983,-0.512481,0.021474,0.025872,0.359484,0.169637,0.383524
1,20170403,13960114,0,4,14,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.469925,...,0.263388,-0.670622,0.853022,0.311651,-0.541371,0.021448,0.025818,0.359484,0.169637,0.383524
2,20170404,13960115,0,4,14,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.309635,...,0.263388,-0.670622,0.853022,0.311651,-0.541371,0.021448,0.025818,0.359484,0.169637,0.383524
3,20170405,13960116,0,4,14,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-2.654028,...,0.263388,-0.670622,0.853022,0.311651,-0.541371,0.021448,0.025818,0.359484,0.169637,0.383524
4,20170408,13960119,0,4,14,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.876339,...,0.263388,-0.670622,0.853022,0.311651,-0.541371,0.021448,0.025818,0.359484,0.169637,0.383524
5,20170409,13960120,0,4,14,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.868726,...,0.263388,-0.670622,0.853022,0.311651,-0.541371,0.021448,0.025818,0.393358,0.350022,0.385686
6,20170410,13960121,0,4,15,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,3.992210,...,0.269673,-0.668911,0.840026,0.295158,-0.544868,0.021460,0.025841,0.393358,0.350022,0.385686
7,20170412,13960123,0,4,15,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-2.340824,...,0.269673,-0.668911,0.840026,0.295158,-0.544868,0.021460,0.025841,0.393358,0.350022,0.385686
8,20170415,13960126,0,4,15,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.054650,...,0.269673,-0.668911,0.840026,0.295158,-0.544868,0.021460,0.025841,0.393358,0.350022,0.385686
9,20170416,13960127,0,4,15,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.043643,...,0.269673,-0.668911,0.840026,0.295158,-0.544868,0.021460,0.025841,0.083782,-0.175133,0.078808
10,20170417,13960128,0,4,16,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.287632,...,0.242578,-0.691645,0.829464,0.275977,-0.553488,0.021422,0.025764,0.083782,-0.175133,0.078808
11,20170418,13960129,0,4,16,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.538462,...,0.242578,-0.691645,0.829464,0.275977,-0.553488,0.021422,0.025764,0.083782,-0.175133,0.078808
12,20170419,13960130,0,4,16,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.390625,...,0.242578,-0.691645,0.829464,0.275977,-0.553488,0.021422,0.025764,0.083782,-0.175133,0.078808
13,20170422,13960202,0,4,16,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.000000,...,0.242578,-0.691645,0.829464,0.275977,-0.553488,0.021422,0.025764,0.083782,-0.175133,0.078808
14,20170423,13960203,0,4,16,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.666667,...,0.242578,-0.691645,0.829464,0.275977,-0.553488,0.021422,0.025764,0.272329,-0.699517,0.174074
15,20170424,13960204,0,4,17,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.994018,...,0.234513,-0.701898,0.822794,0.267090,-0.555704,0.021428,0.025776,0.272329,-0.699517,0.174074
16,20170426,13960206,0,4,17,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.879765,...,0.234513,-0.701898,0.822794,0.267090,-0.555704,0.021428,0.025776,0.272329,-0.699517,0.174074
17,20170429,13960209,0,4,17,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.387597,...,0.234513,-0.701898,0.822794,0.267090,-0.555704,0.021428,0.025776,0.272329,-0.699517,0.174074
18,20170430,13960210,0,4,17,4,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.583658,...,0.234513,-0.701898,0.822794,0.267090,-0.555704,0.021428,0.025776,0.428548,0.198705,0.458788
19,20170501,13960211,0,4,18,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.391389,...,0.229112,-0.705498,0.826722,0.279038,-0.547685,0.021412,0.025743,0.428548,0.198705,0.458788
20,20170502,13960212,0,4,18,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.473477,...,0.229112,-0.705498,0.826722,0.279038,-0.547685,0.021412,0.025743,0.428548,0.198705,0.458788
21,20170503,13960213,0,4,18,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.697906,...,0.229112,-0.705498,0.826722,0.279038,-0.547685,0.021412,0.025743,0.428548,0.198705,0.458788
22,20170506,13960216,0,4,18,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.485149,...,0.229112,-0.705498,0.826722,0.279038,-0.547685,0.021412,0.025743,0.428548,0.198705,0.458788
23,20170507,13960217,0,4,18,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.463415,...,0.229112,-0.705498,0.826722,0.279038,-0.547685,0.021412,0.025743,0.696625,0.202703,0.707244
24,20170508,13960218,0,4,19,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.495050,...,0.225223,-0.710618,0.834884,0.285877,-0.549006,0.021380,0.025676,0.696625,0.202703,0.707244
25,20170509,13960219,0,4,19,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.691542,...,0.225223,-0.710618,0.834884,0.285877,-0.549006,0.021380,0.025676,0.696625,0.202703,0.707244
26,20170510,13960220,0,4,19,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.303644,...,0.225223,-0.710618,0.834884,0.285877,-0.549006,0.021380,0.025676,0.696625,0.202703,0.707244
27,20170513,13960223,0,4,19,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.000000,...,0.225223,-0.710618,0.834884,0.285877,-0.549006,0.021380,0.025676,0.696625,0.202703,0.707244
28,20170514,13960224,0,4,19,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.015228,...,0.225223,-0.710618,0.834884,0.285877,-0.549006,0.021380,0.025676,-0.195355,0.292789,-0.159632
29,20170515,13960225,0,4,20,5,2017,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.102564,...,0.227740,-0.713306,0.829329,0.291555,-0.537773,0.021389,0.025694,-0.195355,0.292789,-0.159632
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,20190518,13980228,0,4,20,5,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,4.883227,...,0.170206,-0.730065,0.584340,0.356050,-0.228290,0.012040,0.016001,-0.766457,-0.906182,-0.767312
206,20190520,13980230,0,4,21,5,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,4.527814,...,0.213460,-0.688636,0.549685,0.414543,-0.135142,0.012439,0.016557,-0.766457,-0.906182,-0.767312
207,20190522,13980301,0,4,21,5,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,4.869359,...,0.213460,-0.688636,0.549685,0.414543,-0.135142,0.012439,0.016557,-0.766457,-0.906182,-0.767312
208,20190525,13980304,0,4,21,5,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-2.038505,...,0.213460,-0.688636,0.549685,0.414543,-0.135142,0.012439,0.016557,NaN,NaN,NaN
209,20190529,13980308,0,4,22,5,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,4.968288,...,0.215481,-0.677824,0.542122,0.448908,-0.093214,0.012818,0.017043,-1.000000,-1.000000,-1.000000
210,20190603,13980313,0,4,23,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,4.224059,...,0.259221,-0.632172,0.521881,0.489847,-0.032034,0.013179,0.017474,-1.000000,-1.000000,-1.000000
211,20190608,13980318,0,4,23,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.057269,...,0.259221,-0.632172,0.521881,0.489847,-0.032034,0.013179,0.017474,0.187854,0.026893,0.092234
212,20190610,13980320,0,4,24,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-3.371298,...,0.210829,-0.673079,0.494202,0.422629,-0.071574,0.012908,0.017155,0.187854,0.026893,0.092234
213,20190612,13980322,0,4,24,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.210654,...,0.210829,-0.673079,0.494202,0.422629,-0.071574,0.012908,0.017155,0.187854,0.026893,0.092234
214,20190615,13980325,0,4,24,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-4.066986,...,0.210829,-0.673079,0.494202,0.422629,-0.071574,0.012908,0.017155,0.929254,0.865766,0.932044
215,20190617,13980327,0,4,25,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.018923,...,0.216017,-0.672183,0.488038,0.418717,-0.069321,0.012835,0.017066,0.929254,0.865766,0.932044
216,20190619,13980329,0,4,25,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-4.308281,...,0.216017,-0.672183,0.488038,0.418717,-0.069321,0.012835,0.017066,0.929254,0.865766,0.932044
217,20190622,13980401,0,4,25,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.450725,...,0.216017,-0.672183,0.488038,0.418717,-0.069321,0.012835,0.017066,1.000000,1.000000,1.000000
218,20190624,13980403,0,4,26,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-0.439453,...,0.199399,-0.685490,0.477189,0.413058,-0.064132,0.012875,0.017115,1.000000,1.000000,1.000000
219,20190626,13980405,0,4,26,6,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.532378,...,0.199399,-0.685490,0.477189,0.413058,-0.064132,0.012875,0.017115,-0.194610,-0.248103,-0.235250
220,20190701,13980410,0,4,27,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-2.100635,...,0.183367,-0.707681,0.473208,0.404984,-0.068224,0.012881,0.017122,-0.194610,-0.248103,-0.235250
221,20190703,13980412,0,4,27,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,3.348104,...,0.183367,-0.707681,0.473208,0.404984,-0.068224,0.012881,0.017122,-0.194610,-0.248103,-0.235250
222,20190706,13980415,0,4,27,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-2.286803,...,0.183367,-0.707681,0.473208,0.404984,-0.068224,0.012881,0.017122,0.875660,0.836513,0.913293
223,20190708,13980417,0,4,28,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.892857,...,0.157966,-0.730985,0.427490,0.369985,-0.057505,0.012963,0.017221,0.875660,0.836513,0.913293
224,20190710,13980419,0,4,28,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.753555,...,0.157966,-0.730985,0.427490,0.369985,-0.057505,0.012963,0.017221,0.875660,0.836513,0.913293
225,20190713,13980422,0,4,28,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-4.704238,...,0.157966,-0.730985,0.427490,0.369985,-0.057505,0.012963,0.017221,0.983295,0.968062,0.957654
226,20190715,13980424,0,4,29,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,3.756098,...,0.157639,-0.738375,0.456869,0.364745,-0.092125,0.012797,0.017017,0.983295,0.968062,0.957654
227,20190717,13980426,0,4,29,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-3.882064,...,0.157639,-0.738375,0.456869,0.364745,-0.092125,0.012797,0.017017,0.983295,0.968062,0.957654
228,20190720,13980429,0,4,29,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-3.783231,...,0.157639,-0.738375,0.456869,0.364745,-0.092125,0.012797,0.017017,-1.000000,1.000000,-1.000000
229,20190731,13980509,0,4,31,7,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-1.774194,...,0.140082,-0.744376,0.437312,0.308519,-0.128793,0.012536,0.016690,-1.000000,1.000000,-1.000000
230,20190803,13980512,0,4,31,8,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,-3.612479,...,0.140082,-0.744376,0.437312,0.308519,-0.128793,0.012536,0.016690,NaN,NaN,NaN
231,20190805,13980514,0,4,32,8,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,2.469845,...,0.135081,-0.754032,0.411717,0.286517,-0.125201,0.012523,0.016673,0.818835,0.812051,0.799869
232,20190819,13980528,0,4,34,8,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,2.953368,...,0.123153,-0.773419,0.379609,0.315948,-0.063661,0.012820,0.017048,0.818835,0.812051,0.799869
233,20190821,13980530,0,4,34,8,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,0.805234,...,0.123153,-0.773419,0.379609,0.315948,-0.063661,0.012820,0.017048,0.818835,0.812051,0.799869
234,20190824,13980602,0,4,34,8,2019,انبوه سازی، املاک و مستغلات,سرمایه گذاریها,1.148278,...,0.123153,-0.773419,0.379609,0.315948,-0.063661,0.012820,0.017048,NaN,NaN,NaN

In [ ]:
data = pd.DataFrame()
gg = df.groupby(['id'])

for i in gg.groups.keys():
    g = gg.get_group(i)
    F_id = g.id.iloc[0]
    print('Id ' + str(F_id) , end="\r", flush=True)
    Next_df = df[df.id > F_id]
    S_gg = Next_df.groupby(['id'])
    data = data.append(S_gg.apply(FCAPf , g = g ))

In [ ]:
d = data.reset_index(drop = True)

In [ ]:
symbols = list(set(df.symbol))
symbols.sort()
ids = list(range(len(symbols)))
mapingdict = dict(zip(ids,symbols))
d['symbol_x'] = d['id_x'].map(mapingdict)
d['symbol_y'] = d['id_y'].map(mapingdict)

In [ ]:
def add(row):
    if len(row)<2:
        row = '0'+ row
    return row
d['month_of_year'] = d['month_of_year'].astype(str).apply(add )
d['week_of_year'] = d['week_of_year'].astype(str).apply(add )


d['year_of_year'] = d['year_of_year'].astype(str)

d['Year_Month_week'] = d['year_of_year'] + d['month_of_year'] + d['week_of_year']
d['Year_Month'] = d['year_of_year'] + d['month_of_year']

days = list(set(d.date))
days.sort()
t = list(range(len(days)))
mapingdict = dict(zip(days, t))
d['t'] = d['date'].map(mapingdict)

days = list(set(d.Year_Month_week))
days.sort()
t = list(range(len(days)))
mapingdict = dict(zip(days, t))
d['t_Week'] = d['Year_Month_week'].map(mapingdict)

days = list(set(d.Year_Month))
days.sort()
t = list(range(len(days)))
mapingdict = dict(zip(days, t))
d['t_Month'] = d['Year_Month'].map(mapingdict)


d['id'] = d['symbol_x'] + d['symbol_y']
ids = list(set(d.id))
ids.sort()
id = list(range(len(ids)))
mapingdict = dict(zip(ids, id))
d['id'] = d['id'].map(mapingdict)

def NormalTransform(df_sub):
    col = df_sub.transform('rank')
    return (col-col.mean())/col.std()


gg = d.groupby(['t'])
d['FCAP*'] = gg['FCAPf'].apply(NormalTransform)
d['FCA*'] = gg['FCA'].apply(NormalTransform)

gg = d.groupby(['t_Week'])
d['WeeklyFCAP*'] = gg['WeeklyFCAPf'].apply(NormalTransform)
d['WeeklyFCA*'] = gg['WeeklyFCA'].apply(NormalTransform)

gg = d.groupby(['t_Month'])
d['MonthlyFCAP*'] = gg['MonthlyFCAPf'].apply(NormalTransform) 
d['MonthlyFCA*'] = gg['MonthlyFCA'].apply(NormalTransform)


gg = d.groupby(['id'])
d['FCAP**'] = gg['FCAPf'].apply(NormalTransform)
d['FCA**'] = gg['FCA'].apply(NormalTransform)

gg = d.groupby(['id'])
d['WeeklyFCAP**'] = gg['WeeklyFCAPf'].apply(NormalTransform)
d['WeeklyFCA**'] = gg['WeeklyFCA'].apply(NormalTransform)

gg = d.groupby(['id'])
d['MonthlyFCAP**'] = gg['MonthlyFCAPf'].apply(NormalTransform) 
d['MonthlyFCA**'] = gg['MonthlyFCA'].apply(NormalTransform)

In [ ]:
d.head().columns
n3 = path + 'NormalzedFCAP5.0.csv'
# d.to_csv(n3,index = False)
print('d done')
a = d.drop_duplicates(['t','id'])
# n3 = path + 'NormalzedFCAP5.1.csv'
a.to_csv(n3,index = False)

Montly =  a.drop_duplicates(['id','t_Month'],keep = "last")
n3 = path + 'MonthlyNormalzedFCAP5.1.csv'
Montly.to_csv(n3,index = False)

Weekly = a.drop_duplicates(['id','t_Week'],keep = "last")
n3 = path + 'WeeklyNormalzedFCAP5.1.csv'
Weekly.to_csv(n3,index = False)


m = 10
f = int(a.id.max()/m)+1
for i in range(m):
    MaId = (i+1)*f
    MiId = (i)*f
    t = a[(a.id < MaId)&((a.id >= MiId))]
    a = a[~(a.id < MaId)]
    t.to_csv(path + "PartedNormalzedFCAP5.1" + "-Part" + str(i+1) + ".csv",index = False)
    print( i +1 ," Done")

In [ ]:
df.head()
df.loc[df.week_of_year%2 == 1,'week_of_year'] = df.loc[df.week_of_year%2 == 1]['week_of_year']-1
Rdf = df.drop_duplicates(['date','symbol'])
dgg = Rdf.groupby(['id'])

a = d.drop_duplicates(['t','id'])

# gg = a.groupby('id')
SId = df[['id','symbol']].drop_duplicates().reset_index(drop = True)
GData = df[['group_name','id']].drop_duplicates().reset_index(drop = True)
Pairs = a[['id_x', 'id_y','id']].drop_duplicates().reset_index(drop = True)
timeId = a[['date','t','t_Week','t_Month']].drop_duplicates().sort_values(by=['t'])


##dgg.to_csv(path + "dgg" + ".csv",index = False)
SId.to_csv(path + "SId" + ".csv",index = False)
GData.to_csv(path + "GData" + ".csv",index = False)
Pairs.to_csv(path + "Pairs" + ".csv",index = False)
timeId.to_csv(path + "timeId" + ".csv",index = False)